version: "3"
services:
  web_jenkins2:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3000:3000"
    volumes: 
      - ./jenkins2:/opt/app
      - gem_cache_jenkins2:/gems
    env_file: 
      - .env/development/database_jenkins2
      - .env/development/web_jenkins2
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_jenkins2
    networks:
      - network
  webpack_dev_server_jenkins2:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3035:3035"
    volumes: 
      - ./jenkins2:/opt/app
      - gem_cache_jenkins2:/gems
    env_file: 
      - .env/development/database_jenkins2
      - .env/development/web_jenkins2
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_jenkins2:
    image: postgres
    env_file: 
      - .env/development/database_jenkins2
    volumes: 
      - db_data_jenkins2:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_jenkins2:
  gem_cache_jenkins2:
networks:
  network: