version: "3" 
services:
  web_jenkins2:
    image: alexrogna/jenkins2_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_jenkins2
      - .env/production/web_jenkins2
    environment:
      - VIRTUAL_HOST=jenkins2.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=jenkins2.alexrogna.com
    networks:
      - proxy
    restart: always

  database_jenkins2:
    image: postgres
    env_file:
      - .env/production/database_jenkins2
    volumes:
      - db_data_jenkins2:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_jenkins2:
    image: alexrogna/jenkins2_web:prod
    command: ["./wait-for", "--timeout=300", "database_jenkins2:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_jenkins2
      - .env/production/web_jenkins2
volumes:
  db_data_jenkins2:
networks:
  proxy: